### ISSUE TITLE
Support nested views

### ISSUE THREAD

**Issue by OrangeDog** [MCMicS/jenkins-control-plugin#115]
A Jenkins server (e.g. using the [Nested View Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Nested+View+Plugin)) can have views/folders nested to an arbitrary depth.
The plugin, however, only lists the first two levels in the drop-down, omitting further subviews and any jobs therein.

**Comment by DvirLevanon** [comment]
seconed that ^

**Comment by MCMicS** [comment]
Maybe solved with #141
