### ISSUE TITLE
[Improvement] View test results directly in IntelliJ IDEA

### ISSUE THREAD

**Issue by LomaPL** [MCMicS/jenkins-control-plugin#125]
Hi all,

I'm test automation engineer and I recently made a switch from Eclipse to IntelliJ IDEA. I have numerous jobs that execute tests nightly and every once in a while a test fails. Mylyn Builds plugin for Eclipse allows you to view the failures and even quickly navigate to the place where the test failed by clicking on the appropriate line in the stacktrace. This is the feature I miss the most in Jenkins Control Plugin.
Any chance of adding such feature in the foreseeable future?

Thanks

**Comment by MCMicS** [comment]
Have a look at 0.11.0m
There you can show log and then test results
