### ISSUE TITLE
Multibranch pipeline builds not shown

### ISSUE THREAD

**Issue by pcornelissen** [MCMicS/jenkins-control-plugin#141]
Now that the crumb issue is gone I'm faced with the next obstacle. I only see the name of the pipelines with the corresponding "weather symbol" but not the real builds. I have created some views for the UI and when I select one of these I see the branch builds, but then the pipeline is not visible, so I just see 30x develop and 30x master without any more explanation.

It would be neat to have pipeline support in the plugin in one way or another.

**Comment by NathanvanDalen** [comment]
I agree. It is very weird to see that one plugin does not have the ability to be able to specify up till what part you want the name not visible (Jan molaks buildmonitor plugin) and the other one does not let you specify which part (from the same view) you are actually able to see.

Now I have to two monitors from which one is showing too much and the other one to less. :man_facepalming: 

Would be really appreciated to at least have the full name (which is available) visible. Now I have 3 PR's 15 `develop` and 15 `master` and I have no idea which is which.

**Comment by CeccoCQ** [comment]
+1

**Comment by henryborchers** [comment]
I love this plugin. It make my life a lot easier. However, it could use a little update. 
Multibranch pipelines are what I use these days and I will be using from now on but I'm not able to fully use it within this plugin. In the sidebar, I can see my multibranch project but I cannot see the branches it contains.  
@dboissier, do you plan on continuing to develop your awesome plugin?

**Comment by MCMicS** [comment]
An EAP version is online: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/update/79077

If you want to try it and found issues or  so please let me know

**Comment by Kisty** [comment]
Thanks for this! I've tried it and I can see the branches for the project 👍. However, the My Favorite filter is now broken. 

I would love to be able to favorite branches so that I can see the current branch I'm working on when I select My Favorites.

**Comment by MCMicS** [comment]
thanks for feedback. I will have a look on it

**Comment by MCMicS** [comment]
I've created an fix which load nested Jobs in favorite View. Also I check Url to determine favorite job.
May you can give it try

EAP2: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/update/79468

**Comment by jin123d** [comment]
> An EAP version is online: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/update/79077
> 
> If you want to try it and found issues or so please let me know

Will it support android studio 3.6.1 in the future?

Android Studio 3.6.1
Build #AI-192.7142.36.36.6241897, built on February 27, 2020

**Comment by MCMicS** [comment]
The release 0.12.0 will contain an version for platform version 183 to 193 (idea 2018+) so it should work with latest android studio.
I will test it these days. I could create an EAP if you want to test it

In Issue #179 it is possible to vote for product and versions

**Comment by Kisty** [comment]
Sorry, forgot to mention. EAP2 worked flawlessly! Thanks again!

**Comment by MCMicS** [comment]
thanks for feedback. I currently prepare the release 0.12.0.
So this feature will be included then

**Comment by jin123d** [comment]
> The release 0.12.0 will contain an version for platform version 183 to 193 (idea 2018+) so it should work with latest android studio.
> I will test it these days. I could create an EAP if you want to test it
> 
> In Issue #179 it is possible to vote for product and versions

yep，I want to test it，the version is `Build #AI-192.7142.36.36.6241897`，thank you

**Comment by MCMicS** [comment]
@jin123d I've create the release because no error was found until now
