### ISSUE TITLE
Password won't save and generates an error upon webstorm bootup

### ISSUE THREAD

**Issue by francissalvamantePTX** [MCMicS/jenkins-control-plugin#150]
So far, I have been using Jenkins Plugin for WebStorm without encountering issues before late last week. It gives me this error **"secret_password_lookup_sync error code 32720, error message null"**. So in order to use Jenkins Plugin, I have to reenter my password everytime WebStorm boots up. How can I possibly fix this issue?

**Comment by MCMicS** [comment]
This seem to be an IDEA Bug.
This should be an issue with the credentials store (missing KWallet, gnome-keyring ...) . if it still occurs please change the credential store:

> Settings | Appearance & Behavior | System Settings | Passwords

see:
https://youtrack.jetbrains.com/issue/IDEA-163613
https://youtrack.jetbrains.com/issue/IDEA-174903

Please feel free to reopen it
