### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by kolisko** [MCMicS/jenkins-control-plugin#153]
Hi,

thank you for great plugin! Could I ask you very kind to add to your feature list following?

- [ ] double click on job run build
- [x] browse jenkins folders. Now I can see the folders but no way to go into it to see jobs and run jobs.
- [x] add filter to show only favorites jobs
- [ ] RSS filter - now event log shows jenkins messages from all jobs. Is possible to filter it, for instance based on selected view filter?

Thanks!!!
Michal

**Comment by igreenfield** [comment]
I will vote for the folders browse!!!

**Comment by jjoselv** [comment]
Also add a enable/disable check/slide, in case jaenkins server is down, it does, not try to reconnect every time.

**Comment by netdesk** [comment]
+1 for folder support!

**Comment by haukekern** [comment]
+1 for folder support!

**Comment by MCMicS** [comment]
Folder support in #128

**Comment by MCMicS** [comment]
moved to new separate issues
@kolisko thanks for feedback
