### ISSUE TITLE
Cant see jobs

### ISSUE THREAD

**Issue by Steveneau** [MCMicS/jenkins-control-plugin#154]
Hello,

I'm not able to see the jenkins jobs in IntelliJ.
Test connection to the server is successful and every checkbox is checked in the build status filter.

Here is the printscreen of what i can see inside the plugin : http://hpics.li/7839aa0

IntelliJ version: 2017.2.5
Jenkins version: 2.73.3
Jenkins control plugin version: 0.10.2016

Do you have any idea to help me ?
Thanks

**Comment by MCMicS** [comment]
If error still occurs with 0.11.0 please feel free to reopen.
