### ISSUE TITLE
"Unknown parameter" for "Extensible Choice" parameters

### ISSUE THREAD

**Issue by sebastienbonami** [MCMicS/jenkins-control-plugin#159]
Hi, this plugin shows "Unknown parameter" when the Jenkins job has a "Extensible Choice" parameter. I guess this plugin is not compatible with "Extensible Choice" parameters?

Thanks!

**Comment by kapoorlakshya** [comment]
Same for `Label` parameter.

**Comment by AlexCzar** [comment]
All the choice params are like that - e.g. git branch_or_tag, ssh creds, etc.

**Comment by MCMicS** [comment]
Textbox Parameter referenced in: #80

**Comment by MCMicS** [comment]
https://github.com/ikedam/extensible-choice-parameter/issues/39

**Comment by MCMicS** [comment]
Do you have a correct sample to support.

Following should be possibe via API.
Configuration: 
![grafik](https://user-images.githubusercontent.com/4604206/104951511-f393a880-59c2-11eb-87ea-05efbd86b3c4.png)

API:
![grafik](https://user-images.githubusercontent.com/4604206/104951547-04441e80-59c3-11eb-8ca6-27616f0f7201.png)

**Comment by MCMicS** [comment]
released with [0.13.12](../releases/tag/v0.13.12)
