### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by kurtisane** [MCMicS/jenkins-control-plugin#165]
Hi, 
I´m having issues setting up the plugin. 
My server adress ist http://myserveradress:8080/ and all the other informations are given also. 
When I test the connection it is working corretly but when I apply I´m getting that Error message on the top right. 

> IO Error during method execution 'http://myserveradress:8080//api/json?tree=name,url,jobs%5Bname,displayName,url,color,buildable,inQueue,healthReport%5Bdescription,iconUrl%5D,lastBuild%5Bid,url,building,result,number,timestamp,duration%5D,property%5BparameterDefinitions%5Bname,type,defaultParameterValue%5Bvalue%5D,choices%5D%5D%5D': Read timed out

What is causing that issue and how can I fix that ? 

Regards !

**Comment by MCMicS** [comment]
timeout is now configurable. If it still happens please reopen
