### ISSUE TITLE
why the port must be 8080 ?

### ISSUE THREAD

**Issue by caiqichang** [MCMicS/jenkins-control-plugin#166]
my jenkins's port is 8180, test connection is successful, 
but the plugin shows: 
Jenkins Server Port Mismatch: expected='8180' - actual='8080'. Look at the value of 'Jenkins URL' at http://localhost:8180//configure

**Comment by Geminii** [comment]
@caiqichang if you define the port as 8180, you need to change it into Jenkins location configuration.

**Comment by MCMicS** [comment]
Closed because it is configuration problem
Thx @Geminii
