### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by NotSoImportant** [MCMicS/jenkins-control-plugin#169]
Hi, I think this is a really helpful plugin.
Is it still maintained?
The last commit was from 1 year ago...
Thank you

**Comment by NotSoImportant** [comment]
I would be at least insterested in a fix for (or help to myself fix) https://github.com/dboissier/jenkins-control-plugin/issues/167
Because this really makes it unusable for me, because I often need to work on multiple projects in parallel.

**Comment by cezary-butler** [comment]
Within a week I'll try to prepare some hints for you to help you fix it. Please prepare development environment for the plugin during that time.

**Comment by NotSoImportant** [comment]
Thank you very much.
Is there documentation what's needed to develop this plugin? I have not done IntelliJ plugin development before.

**Comment by cezary-butler** [comment]
Jetbrains has quite good documentation here: https://www.jetbrains.com/help/idea/plugin-development-guidelines.html
Please take note of any difficulties you'll have during setting up project, it can be used to overcome them or put relevant information in Readme.

**Comment by NotSoImportant** [comment]
Thank you. I've cloned, imported into IntelliJ and gradle build is working fine, however Run/Debug the plugin seems not so easy.
First followed the description of https://stackoverflow.com/questions/18278440/how-to-import-and-run-existing-plugins-from-intellij-community-edition-repo
how to get the run config enabled.
But after that there is no guidance on how to do it:
http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/running_and_debugging_a_plugin.html
When I press run or debug ("main" module) I end up with a new IntelliJ window, not having the plugin installed/enabled. Not sure what I need to do there.
I could maybe continue with blindly fixing the code with your help (or change, deploy, validate cycles) however there should be a better way, isn't it?

**Comment by MCMicS** [comment]
it is possible to add an additional maintainer or contributer with merge rights?
So this project will be active.

@dboissier Can you grant access

**Comment by MCMicS** [comment]
Good news guys. It seems that this project will still alive and maintained.

**Comment by Geminii** [comment]
Hey guys,
Excellent 😀😀 
Available to help to fix bugs and improve it 👍

**Comment by MCMicS** [comment]
Good to know. Thanks for help.
You can look for an issue and solve it.
Currently i work on multibranch feature and 2020.1 support

**Comment by Geminii** [comment]
@MCMicS I look at the project. 
Multibranch doesn't work for 2019.2 version. Only for latest 2019.3 version ? 
Which one need to be solved asap ? Possible to discuss on discord, gitter (already available or not) ?

**Comment by MCMicS** [comment]
Gitter is available.
Not sure if 2018 should supported. Currently only 2019+ is developed.

May be we do an 2018 version if needed
