### ISSUE TITLE
Vote for Supported Products

### ISSUE THREAD

**Issue by MCMicS** [MCMicS/jenkins-control-plugin#179]
Hi all,

For which Idea products this plugin should be compatible?

0.10.0: could be used in all Products
0.11.0: Currently only works in IntelliJ

![grafik](https://user-images.githubusercontent.com/4604206/73613143-07e46700-45f3-11ea-97e7-de0a882a6708.png)

So let me know which products are you using and should be supported.

EAP Version: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/update/77175

**Comment by MCMicS** [comment]
I'll try to enable support for all and handle it with optional depends

**Comment by RobinRadic** [comment]
phpstorm please

**Comment by MCMicS** [comment]
I have marked the JUnit dependency as optional. So it should be work in all product again

see EAP2: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/update/77244

**Comment by MCMicS** [comment]
Support for:
Android Studio 3.6.1
Build #AI-192.7142.36.36.6241897, built on February 27, 2020
