### ISSUE TITLE
Feature Request: Offer option to use green balls instead of blue ones

### ISSUE THREAD

**Issue by gonozalviii** [MCMicS/jenkins-control-plugin#183]
In Jenkins, there is the Green Balls Plugin.
Maybe you can add Green Balls as an option to use instead of blue ones.

**Comment by MCMicS** [comment]
Could be possible. Will try to do it in next release.

**Comment by MCMicS** [comment]
included in EAP3: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/update/79976
