### ISSUE TITLE
Trigger Build on Double click

### ISSUE THREAD

**Issue by MCMicS** [MCMicS/jenkins-control-plugin#190]
copied from #153 

double click on job run build

**Comment by Majed6** [comment]
Hi,

Is it possible to make double click load builds instead ? I keep on double clicking by mistake.

Thanks

**Comment by MCMicS** [comment]
Yes it is possible. I can add an setting to determine double click action.

**Comment by Majed6** [comment]
That would be lovely. Thanks a bunch for the prompt response and interest. 




 <https://dee.codes/>




Jul 11, 2021, 15:22 by ***@***.***:

**Comment by MCMicS** [comment]
I have created feature Request #298 for this
