### ISSUE TITLE
[Feature request] Show log for individual builds of selected jobs

### ISSUE THREAD

**Issue by tillias** [MCMicS/jenkins-control-plugin#197]
Hello,

It would be nice to have the possibility of looking into individual logs per build. Is it showing log for the latest successful / failed build?

**Comment by MCMicS** [comment]
Sounds good.

**Comment by MCMicS** [comment]
What do you think about following suggestion:
Add show log for selected Build?
**Build**
`> Show Log`
 
Show latest log (success or failure) on Job:
**Job**
`> Show Logs`
`>> Last Successful`
`>> Last Failure`

**Comment by tillias** [comment]
Great idea. For me (personally) the most common case is to check output for current (latest) build.

**Comment by MCMicS** [comment]
For mee too. Only the last log is most relevant.
I will schedule it for next release

**Comment by MCMicS** [comment]
Implement for selected Jobs:
![grafik](https://user-images.githubusercontent.com/4604206/90554311-f11fef00-e195-11ea-86e1-36ce38070fd6.png)

For Build the Goto Jenkins is available:
![grafik](https://user-images.githubusercontent.com/4604206/90554363-072daf80-e196-11ea-936c-0de21b5819b5.png)

It would be great if you can test it and give feedback for this.
This will be release this week if no errors are found.

EAP Version: 
[jenkins-control-plugin-0.13.8-2020.1-eap3.zip](https://github.com/MCMicS/jenkins-control-plugin/files/5092342/jenkins-control-plugin-0.13.8-2020.1-eap3.zip)
Upload TO IDEA currently not working. Will try it again later
