### ISSUE TITLE
Error reading jenkins.diff file

### ISSUE THREAD

**Issue by guptaricha98** [MCMicS/jenkins-control-plugin#201]
![Error](https://user-images.githubusercontent.com/64438134/80415673-dcdf7b80-88a0-11ea-91fd-bf22d36d71b8.jpg)

**Comment by MCMicS** [comment]
Hi. What are your steps to reproduce it?

**Comment by guptaricha98** [comment]
Steps to reproduce:
1. Update a file.
2. Right click and select ''Create Path and Build on Jenkins''.
3. In 'Create Path and Build on Jenkins' pop-up window, select job name.
4. Click 'OK'.

Intellij IDEA: 2019.3.4
Build #IC - 193.6911.18

Jenkins Control Plugin: 0.12.0

**Comment by MCMicS** [comment]
I have a look at it.

**Comment by MCMicS** [comment]
do you have a stacktrace?
On my machine it works currently. I test more

**Comment by MCMicS** [comment]
with 20196.3.4 I've got:
```
java.lang.Throwable: Assertion failed: Write access is allowed inside write-action only (see com.intellij.openapi.application.Application.runWriteAction())
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:180)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertWriteAccessAllowed(ApplicationImpl.java:1174)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$2.close(PersistentFSImpl.java:638)
	at org.codinjutsu.tools.jenkins.view.action.UploadPatchToJob.prepareFile(UploadPatchToJob.java:145)
	at org.codinjutsu.tools.jenkins.view.SelectJobDialog.uploadPatchForJob(SelectJobDialog.java:209)
	at org.codinjutsu.tools.jenkins.view.SelectJobDialog.onOK(SelectJobDialog.java:190)
	at org.codinjutsu.tools.jenkins.view.SelectJobDialog.access$000(SelectJobDialog.java:48)
	at org.codinjutsu.tools.jenkins.view.SelectJobDialog$1.actionPerformed(SelectJobDialog.java:82)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)

```

**Comment by guptaricha98** [comment]
> stacktrace

[threadDump-20200428-113334.txt](https://github.com/MCMicS/jenkins-control-plugin/files/4547975/threadDump-20200428-113334.txt)
Is this what you are asking for?

**Comment by MCMicS** [comment]
No.
If the error occuirs the normaly the error notify should apper on the right lower. If you click on it you see the stacktrack for it.
![grafik](https://user-images.githubusercontent.com/4604206/80527097-2066e200-8994-11ea-8ff5-c3abaab54812.png)

**Comment by MCMicS** [comment]
I'm currently change the file location to temp folder. It is bestter to use this instead of using the bin folder of IDEA.
I try to create an eap version this day

**Comment by guptaricha98** [comment]
There is no stacktrace for "Build cannot be run: jenkins.diff (Access Denied)" error.

Thank you for picking this up.

**Comment by MCMicS** [comment]
OK.

I cannot reproduce it but make the changes with the wrong patch location and fix the write error. Maybe your error is also gone then

**Comment by MCMicS** [comment]
Would you please test this version: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/update/85072

If you add 'https://plugins.jetbrains.com/plugins/eap/list' to repositries it wil lbe offer also within IDEA

**Comment by guptaricha98** [comment]
Yes, the error is gone. Triggering build from within IDE is working fine now. However, I don't see my local file changes in jenkins build logs.

Does this plugin works with GIT or just SVN?

**Comment by MCMicS** [comment]
Should both work. I've tested Git wit this build

**Comment by MCMicS** [comment]
I've tests it with Git and it should work.
what say you jenkins log?

something like following should be found:

> Copying file to patch.diff
> Applying a patch
> Parsing POMs

**Comment by guptaricha98** [comment]
Hi Michael,
Thank you for sharing the information. It still isn't working for me. May be some configuration problem. May we discuss about on email?

And I am happy to close this bug, since it is fixed.

**Comment by MCMicS** [comment]
Hi,
i could help you. Maybe we use the gitter chat or mail or discord/ts screen sharing. what do u prefer

**Comment by guptaricha98** [comment]
Yes. I tried your sample project and it works fine. So, this plugin works fine with maven jobs in jenkins, but I was trying to test patch for Pipeline job. And, I think this is the reason why things are not working for me.

**Comment by MCMicS** [comment]
Have you a sample jenkinsfile to test it?
do you use declarative or scripted pipeline. If you have a pipeline script I can try to help

**Comment by guptaricha98** [comment]
Sure. I will put a sample project later today. Also gitter chat is good.

**Comment by MCMicS** [comment]
I have create a small scripted pipeline (https://github.com/MCMicS/UploadPatchToJenkins/tree/pipeline) but if I use Build from Jenkins and select patch my test will still fail

Maybe the Patch Plugin not support pipeline 8because it outdated)
