### ISSUE TITLE
NodeParameterDefinition is unsupported

### ISSUE THREAD

**Issue by Umeshpawar1990** [MCMicS/jenkins-control-plugin#213]
![image](https://user-images.githubusercontent.com/65715148/82557325-dc3fb980-9bae-11ea-8d2b-1c47f5b77d08.png)
NodeParameterDefinition is unsupported

**Comment by MCMicS** [comment]
not all plugin with its parameters are implemented.
But i can have a look if all needed data are available

Which plugin is it?

**Comment by Umeshpawar1990** [comment]
Plugin name is Jenkins Control Plugin. I set Node for execution in jenkins
jobs using Node Parameter.

**Comment by MCMicS** [comment]
I mean the plugin which offers node as paramters on Jenkins

Do you have following: https://plugins.jenkins.io/nodelabelparameter/

**Comment by Umeshpawar1990** [comment]
Yes I have the same plugin.

**Comment by MCMicS** [comment]
ok
I looked at the API of the plugin and I no get the available nodes for parameter because its not implement the API correct and is not maintained for last 4 years.

![grafik](https://user-images.githubusercontent.com/4604206/82559548-1fc70300-9b70-11ea-9ea8-4b5a2f77e46e.png)

Is a custom Input Field correct for your needs or do you need a listbox with available nodes(which needs more effort)?

**Comment by Umeshpawar1990** [comment]
I would pefer listbox as it will give more effectivce solution for me.

**Comment by MCMicS** [comment]
OK.
A list box with all nodes should possible. But withouzt any logic klike the jenkins Ui will offer. 
I mean. You can define which nodes are avaialable for parameter but due the missing API of the Node Plugin in Jenkins I cannot get the information. So you will see always all nodes.

Is this right for you?

**Comment by Umeshpawar1990** [comment]
Yes that way I will get an option to select node before triggering jenkins
job.

**Comment by MCMicS** [comment]
OK
I implement this in one of the next releases

**Comment by Umeshpawar1990** [comment]
Thanks for your prompt reply and action for issue resolution.

**Comment by Umeshpawar1990** [comment]
Any updates

**Comment by MCMicS** [comment]
Not yet. Will try to update this week

**Comment by Umeshpawar1990** [comment]
Means no solution for NodeParameterdefinition ?

**Comment by MCMicS** [comment]
> Means no solution for NodeParameterdefinition ?
No it is fixed but not merged yet. I test it currently and with 0.13.3 it will released

**Comment by Umeshpawar1990** [comment]
So when you are planning to deploy it

**Comment by MCMicS** [comment]
Due date is sunday. Have one issue left in milestone.
Will fix the last issue today if time permits

**Comment by MCMicS** [comment]
If you want to pre test it I uploaded an EAP version (2020 only)
Link: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/update/87312

**Comment by MCMicS** [comment]
released with [0.13.3](../releases/tag/v0.13.3)

**Comment by Umeshpawar1990** [comment]
Working perfectly fine.
