### ISSUE TITLE
login fails with OpenShift login redirect

### ISSUE THREAD

**Issue by diman82** [MCMicS/jenkins-control-plugin#214]
My jenkins instance is running as a pod in OpenShift, and login is done using OpenShift credentials.
But login fails with this plugin.

Is there a way to configure plugin to authenticate through OpenShift?

**Comment by MCMicS** [comment]
Have not tested it yet. Is your server available for test.
If not I have to create a own to test

**Comment by diman82** [comment]
My server is in an enterprise environment, so a bit limited..

**Comment by MCMicS** [comment]
Have you tried to use an jenkins api token for login?
Or get you some error message during login?

I will try to setup a test these days

**Comment by diman82** [comment]
I've created Jenkins api token, but I can't input it, as I'm being redirected to Openshift login page.
inputting api token in your plugin password field still yields 'bad credentials' (and no debug info).

> Do you also use this plugin:
> https://github.com/openshift/jenkins-openshift-login-plugin

Yes, I think this is the correct plugin, but not 100% sure what is being used (I haven't been involved in the infrastructure setup.

Thanks, will wait for your results.

**Comment by MCMicS** [comment]
OAuth Token are currently not implemented

Maybe in some of the next releases

Similar like this: #50

**Comment by MCMicS** [comment]
Could you try to use API token as Password.

In my setup it works (only PyStorm not works correctly)

**Comment by diman82** [comment]
> Could you try to use API token as Password.
> 
> In my setup it works (only PyCharm not works correctly)

Ok, it worked.
P.S. It's required to add '-edit-view' to given name, e.g. myname-edit-view

**Comment by MCMicS** [comment]
works with latest release: 

Test instance: https://jenkins-mcmics-dev.apps.sandbox-m3.1530.p1.openshiftapps.com/

![grafik](https://user-images.githubusercontent.com/4604206/229584131-743a9b3d-b773-40c4-84cf-c1eedcdd750e.png)
![grafik](https://user-images.githubusercontent.com/4604206/229584149-a85f9b9a-d10e-47a9-aba3-5d4271d630ae.png)
