### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by AnkemVishnu** [MCMicS/jenkins-control-plugin#215]
Hi,
I'm having issues setting up the plugin.
When I test the connection it is working but when I open views I'm getting an error message.

IO Error during method execution 'https://jenkins.tracfone.com/job/Kubernetes/job/Micro-Services//api/json?tree=name,url,displayName,fullDisplayName,jobs%5Bname,fullName,displayName,fullDisplayName,jobs,url,color,buildable,inQueue,healthReport%5Bdescription,iconUrl%5D,lastBuild%5Bid,url,building,result,number,displayName,fullDisplayName,timestamp,duration%5D,property%5BparameterDefinitions%5Bname,type,defaultParameterValue%5Bvalue%5D,description,choices%5D%5D%5D': Read timed out

![Screenshot (251)](https://user-images.githubusercontent.com/30042795/82939441-00393b80-9fb1-11ea-92f6-ed6baad01f38.png)

What is causing that issue and how can I fix that ?

Regards !

**Comment by MCMicS** [comment]
Hi,
it seems that the server not response within the timeut for the Job 'cop' .

But there are jobs loaded visible as I can see.

Is message message shown on each refresh?

What happen if you open URL in Browser?

If it occurs I should add an configurable timeout setting

**Comment by AnkemVishnu** [comment]
Hi,

yes other jobs are able to load only this specific job is getting Timeout.
And when i open the same URL in browser I'm able to see the response.
 
![Screenshot (252)](https://user-images.githubusercontent.com/30042795/82940392-5eb2e980-9fb2-11ea-814c-94169ed19520.png)

So do u think adding an configurable timeout setting could solve this ??

**Comment by MCMicS** [comment]
How long it loads in browser?

**Comment by AnkemVishnu** [comment]
i clocked 50 sec

**Comment by MCMicS** [comment]
general for all?

maybe configurable I think. I will try to add this in the update this week

**Comment by AnkemVishnu** [comment]
50 sec for the Job which is getting this error.

But it would be great to set 1 min Timeout

**Comment by MCMicS** [comment]
yes. I will create an setting in config dialog so you can configure it for all projects

**Comment by AnkemVishnu** [comment]
Thanks :) 👍

**Comment by MCMicS** [comment]
thanks for feedback for the plugin

**Comment by MCMicS** [comment]
released with [0.13.3](../releases/tag/v0.13.3)
