### ISSUE TITLE
Received fatal alert: unrecognized_name when testing connection

### ISSUE THREAD

**Issue by smeevil** [MCMicS/jenkins-control-plugin#216]
Hi there,

I'm quite excited to use this plugin but alas I'm running into a little problem.
I configure the server, username and password( using my api token) and ver 2.x.
When hitting text connection It returns an IO error:

![CleanShot 2020-05-28 at 16 36 51@2x](https://user-images.githubusercontent.com/13874/83155430-849ad400-a101-11ea-929c-d05ff1cb8db3.png)

Running curl returns :
```
curl -X GET https://ci.xxxxx/api/json?tree=nodeName --user smeevil:xxxx
{"_class":"hudson.model.Hudson","nodeName":""}
```

Would you have any idea what might be going wrong?

I am using IntelliJ IDEA 2020.1 and plugin version 0.13.3-2020.1 and Jenkins 2.233

Gerard.

**Comment by MCMicS** [comment]
This is normally a SSL error or so

But in yout screen is ic.xxx and your curl says ci.xxx

**Comment by smeevil** [comment]
Ye gods I'm such a tool...

Sorry for bothering you, move along, nothing to see here...

(it works fine now:P)

**Comment by MCMicS** [comment]
No problem.
Have a nice day
