### ISSUE TITLE
How to run a jenkins job with hidden fields?

### ISSUE THREAD

**Issue by mmuserll** [MCMicS/jenkins-control-plugin#219]
Hi,

i installed the plugin on intelligIDE 2020.1
the plugin looks very ussfully to my work, unfurtuantly im not able to run jobs with hidden fields
is there a solution for that?

**Comment by MCMicS** [comment]
The hidden parameter plugin ist not supported.
We only support the basic parameters and some additional which was requested.

I can check if I can get needed data for this plugin.

Do you use the the hidden parameter plugin?

Do you get an build dialog with parameter. Normally the default should be used if no value is present

**Comment by mmuserll** [comment]
Thanks for the quick replay!

yes, im using hidden parameter in jenkins job
im getting kind of an error that hide parameter is not supported - see attached screenshot
![image](https://user-images.githubusercontent.com/66352967/83633315-6f162600-a5a9-11ea-9314-ad2003fe5892.png)

**Comment by MCMicS** [comment]
Youre welcome

You closed this issue?
It should be possible to ignore this parameter and not show them in dialog

**Comment by mmuserll** [comment]
sorry, by mistake i closed the issue 

the issue is that the "OK" button is disable due to hidden parameter

**Comment by MCMicS** [comment]
released with [0.13.4](../releases/tag/v0.13.4)

**Comment by mmuserll** [comment]
working fine now with hidden field having default value.
many thanks!
