### ISSUE TITLE
Git Branch Parameter is unsupported

### ISSUE THREAD

**Issue by vaibhavjain93** [MCMicS/jenkins-control-plugin#225]
I have a parameter which is a git branch and is fetched from remote in Jenkins. That parameter is unsupported saying "PT_BRANCH is unsupported".

**Comment by MCMicS** [comment]
Currently a subset of parameters are supported because there are a lot of parameters.
But maybe in one of the next releases.

I need the name of the plug-in to check if all needed data is available via API?

**Comment by vaibhavjain93** [comment]
![image](https://user-images.githubusercontent.com/8111000/84942695-df23c080-b100-11ea-9b74-17a411ef97ba.png)

When I add a parameter I select "git parameter" and it gives me an option of type of parameter. While making the build this fetches the list of all available branches from remote that was specified in the configuration.

**Comment by MCMicS** [comment]
Do you have this installed: https://plugins.jenkins.io/git-parameter/

**Comment by vaibhavjain93** [comment]
Yes
![image](https://user-images.githubusercontent.com/8111000/84943327-d7185080-b101-11ea-94f8-5257b6021f4a.png)

**Comment by MCMicS** [comment]
OK
I'll check the API later. 

If you Jenkins is public I can check against your server

**Comment by vaibhavjain93** [comment]
Its not public.

**Comment by vaibhavjain93** [comment]
You have a great product and very useful. If this can be done I will be able to use it. 
Thanks.

**Comment by MCMicS** [comment]
give me some days. Currently working on File Parameter. Is all data is available via API it should be implemented in some hours.
But i have time next week to look if it is fine to you

**Comment by vaibhavjain93** [comment]
Ya sure. If you can guide me I would love to contribute as well.

**Comment by MCMicS** [comment]
this would help:
To implement you can create an own Renderer (https://github.com/MCMicS/jenkins-control-plugin/blob/master/src/main/java/org/codinjutsu/tools/jenkins/view/extension/JobParameterRenderer.java) and register here https://github.com/MCMicS/jenkins-control-plugin/blob/master/src/main/resources/META-INF/JobParameterRenderer.xml

samples are here: https://github.com/MCMicS/jenkins-control-plugin/blob/master/src/main/java/org/codinjutsu/tools/jenkins/view/parameter/BuiltInJobParameterRenderer.java

to check the API you can call: `<jenkinsUrl>/job/<JobName>/api/json` and look for `property` like this
![grafik](https://user-images.githubusercontent.com/4604206/84945112-21400880-b0e7-11ea-96dd-76b109307302.png)

**Comment by vaibhavjain93** [comment]
Steps to test?

**Comment by MCMicS** [comment]
Test the new renderer for your parameters?

It should work (if possible) like the web version (build with parameter).

You can build the plugin with gradle task buildplugin

If the jenkins plugin offer more than one type all should be added

**Comment by MCMicS** [comment]
I've looked at the API for the plugin and saw that the possible branches not delivered via API.

So it is only possible to implement this behaviour (ehich need Git g´credentials (not recommend) or only offer an Input Field

![grafik](https://user-images.githubusercontent.com/4604206/85370935-cae02900-b52f-11ea-9dc5-97da029d33c2.png)

Or create an issue in the Git Parameter Plugin so that the API deliver choices in the result

**Comment by MCMicS** [comment]
I've create an issue: https://issues.jenkins-ci.org/browse/JENKINS-62777

**Comment by krasnyt** [comment]
If the branch list is not provided through the API, at least a simple input field for the branch name would be sufficient (until there is a proper branch list retrieval possible).

**Comment by vaibhavjain93** [comment]
Yes @krasnyt , this can work as well.

**Comment by MCMicS** [comment]
Yes this is one of my solution. I will add them today and create an eap to test.
Is 2020 idea version ok?

**Comment by krasnyt** [comment]
Yes, 2020.1.2. Thank you.

**Comment by MCMicS** [comment]
Its ready. Testing it currently and in few minutes it will be online in EAP Channel and here as link

**Comment by MCMicS** [comment]
EAP Build: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/update/89816

**Comment by MCMicS** [comment]
released with [0.13.6](../releases/tag/v0.13.6)

**Comment by vaibhavjain93** [comment]
Thanks. I tested it. Works great
