### ISSUE TITLE
jobs in folders: job name too long

### ISSUE THREAD

**Issue by HonoluluHenk** [MCMicS/jenkins-control-plugin#230]
We're using [folders](https://plugins.jenkins.io/cloudbees-folder/) to store jobs.

With about 2 nested folders, the displayed name is so long I have to resize the Jenkins plugins view to see the full name.

Main reason is that this plugin displays a full path (instead of just relative ones) on every level of the tree.

Example Jenkins folder/job structure:
someFolder
  +- otherFolder
      +- Some Jobname

Actual plugin display:
someFolder
  +- someFolder » otherFolder
      +- someFolder » otherFolder » Some Jobname

Expected plugin display:
someFolder
  +- otherFolder
      +- some Jobname

**Comment by MCMicS** [comment]
one reason for the full displayname is the favorite list feature. if you add one of them to favorite list it is easier to detect in which folder the job is nested.

But I understand your  issue. I will think about an alternative to fulfill both

**Comment by MCMicS** [comment]
It is also the display which jenkins use for Queue: 
![grafik](https://user-images.githubusercontent.com/4604206/86036086-9c85b080-ba3d-11ea-96e4-c9a2bc8e8860.png)

**Comment by MCMicS** [comment]
I found good possible solutions. (in my opinion)
1. Show Full Name Only if for first level. displayname anywhere
2. If the parent Job node contains part of current node the parent part is removed

What do you think about that?

**Comment by HonoluluHenk** [comment]
sounds great!

**Comment by MCMicS** [comment]
@HonoluluHenk Could you please 
test this version if it works for your needs?
[jenkins-control-plugin-0.13.7-2020.1-eap3.zip](https://github.com/MCMicS/jenkins-control-plugin/files/4955635/jenkins-control-plugin-0.13.7-2020.1-eap3.zip)

![grafik](https://user-images.githubusercontent.com/4604206/88095468-7e6f2400-cb95-11ea-8570-b996dcfe8d78.png)

**Comment by HonoluluHenk** [comment]
Folder names display beautifully, thanks!

Not sure if this is related: the folder status icon of one folder is not displayed correctly: see screenshot.
I'd expect the same icon (i.e.: the sun) as in one of the jobs
Sun-Icon-URL is: /static/foobar/images/32x32/health-80plus.png
If you want, I can create another issue for this.

![jenkins-plugin-missing-icon](https://user-images.githubusercontent.com/850496/88189788-b7f96b00-cc39-11ea-8573-6f43b838e99a.png)

**Comment by MCMicS** [comment]
Thanks for feedback.
The problem with the health status (sun) was discussed in gitter a time ago. But I think no issue exists currently. So please add an new one.

We've looked into the cause for missing sun but not found any problem yet because it sometimes work and sun is shown.

But i will look more for this

**Comment by MCMicS** [comment]
released with [0.13.7](../releases/tag/v0.13.7)
