### ISSUE TITLE
jobs in folders: collapsed after refresh

### ISSUE THREAD

**Issue by HonoluluHenk** [MCMicS/jenkins-control-plugin#231]
We're using [folders](https://plugins.jenkins.io/cloudbees-folder/) to store jenkins jobs.

After each refresh, an expanded folder structure gets collapsed and you have to click through to my job, again.
Veeeery annoying.

**Comment by MCMicS** [comment]
Hi
Yes its on feature list to restore last state if refresh the view. Expand all previous expanded nodes

**Comment by MCMicS** [comment]
An EAP version for this is uploaded.
If you could check it and give feedback it would be nice.

EAP Build: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/versions/eap/94652

**Comment by MCMicS** [comment]
This only works for Jobs and Branches currently
Build are not reloaded on refresh
