### ISSUE TITLE
PersistentStringParameter not supported

### ISSUE THREAD

**Issue by mliner** [MCMicS/jenkins-control-plugin#232]
Hi,
I would like to use this plugin but I found this issue with most of our jenkins jobs. The fact is that we use PersistentStringParamter very often in dozens of jobs therefore it would be great if you could implement the support (if possible).

Thanks in advance.

![image](https://user-images.githubusercontent.com/7250180/87138643-03596400-c29f-11ea-87f4-c9bf49f0e96a.png)

**Comment by MCMicS** [comment]
Which jenkins plugin offer this parameter?
Then i can check the api and implement this

**Comment by mliner** [comment]
Hi, thanks for the quick response. Here is the plugin documentation https://plugins.jenkins.io/persistent-parameter/

**Comment by MCMicS** [comment]
I will check this later the day.
Maybe an eap will available today

**Comment by MCMicS** [comment]
The API not offer the last value (from previuos build) So it will always use the Default value then

**Comment by MCMicS** [comment]
EAP: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/versions/eap/91583

**Comment by MCMicS** [comment]
released with [0.13.7](../releases/tag/v0.13.7)
