### ISSUE TITLE
Error overlay over whole of screen if connection is lost

### ISSUE THREAD

**Issue by HonoluluHenk** [MCMicS/jenkins-control-plugin#233]
I'm working on a corporate VPN.
Initially, everything works fine.

When the VPN disconnects, an error bubble is presented *repeatedly* over the full width of the screen, telling me that an IOExcpetion happened, blocking my view of the code.

Steps to reproduce:
1. Setup the jenkins plugin with a jenkins job and refresh once
2. Unplug the network cable :)
3. Refresh again

Content of the error bubble:
`IO Error during method execution 'https://somewhere.og/job/myjob//api/json?tree=name,url,jobs%5Bname,fullName,displayName,fullDisplayName,jobs,url,color,buildable,inQueue,healthReport%5Bdescription,iconUrl%5D,lastBuild%5Bid,url,building,result,number,displayName,fullDisplayName,timestamp,duration%5D,property%5BparameterDefinitions%5Bname,type,defaultParameterValue%5Bvalue%5D,description,choices%5D%5D%5D': Connection reset`

This message should - if at all visible - imho be placed in the "Event Log" (typically this is located at the lower right).

Would be even nicer to have a user-friendly message in the plugins' toolbar-view telling me that the connection currently is unavailable.

**Comment by MCMicS** [comment]
related to #144

**Comment by MCMicS** [comment]
I changed the message and the notification to be confugurable. Default is Tool Window Balloon (as previous). If the message is too large for screen it is not shown. It is also possible to configure it (Settings -> Appearance -> Notifications -> Jenkins Notifications) to show only balloon or only log

Could you please give it it try and send feedback.
[jenkins-control-plugin-0.13.7-2020.1-eap2.zip](https://github.com/MCMicS/jenkins-control-plugin/files/4907524/jenkins-control-plugin-0.13.7-2020.1-eap2.zip)

**Comment by MCMicS** [comment]
@HonoluluHenk Could you please give it it try and send feedback.

**Comment by HonoluluHenk** [comment]
Nice, works for me, thanks!

Imho, this needs some documenting on the plugins homepage - or the overview page in the IntelliJ installed plugins view.
The reason being that not that many plugins implement notification configuration in such a nice way and this settings-area is possibly not that well known.

**Comment by MCMicS** [comment]
thanks for feedback. The documentation will be updated on release. This will describe how to change the notification settings

**Comment by MCMicS** [comment]
released with [0.13.7](../releases/tag/v0.13.7)
