### ISSUE TITLE
Can't seem to connect to my jenkins server with the latest version 0.13.6-2020.1

### ISSUE THREAD

**Issue by gardengeek99** [MCMicS/jenkins-control-plugin#234]
![image](https://user-images.githubusercontent.com/1141532/87321386-c9cc6700-c4f1-11ea-8585-5d8ecb00bbae.png)

**Comment by MCMicS** [comment]
Which jenkins version do you have?
Is the server public available?

**Comment by gardengeek99** [comment]
1.620
No, it is on our private network.

**Comment by MCMicS** [comment]
I have a look at this.

Seems like no serverUrl is returned for following call.

Could you send me the json output for: `<jenkinUrl>/api/json/?tree=nodeName,url,description`
and
`<jenkinUrl>/api/json/`

**Comment by MCMicS** [comment]
Can return not null value but it is interesting why it is null at your setup

**Comment by gardengeek99** [comment]
<jenkinUrl>/api/json/?tree=nodeName,url,description
{"nodeName":"","description":null}
<jenkinUrl>/api/json/
Contains content I probably can't share.

**Comment by MCMicS** [comment]
is there anywhere a json field with your serverUrl?

**Comment by MCMicS** [comment]
you can also use private gitter chat or send me an mail. (mcmics84 gmail)

**Comment by gardengeek99** [comment]
Only under jobs array, view array and primaryView.

**Comment by MCMicS** [comment]
thanks
I create an fix for that. Strange is that no url is listed on root level. But Ok. Seems to handle this

**Comment by MCMicS** [comment]
Sorry for the bug. Could you please try following build. If that works I will create an official fix as soon as possible if needed. If not needed an official it will includes in next mile stone 0.13.7 in maybe 1-2 week 

[jenkins-control-plugin-0.13.6-2020.1-bug234.zip](https://github.com/MCMicS/jenkins-control-plugin/files/4914323/jenkins-control-plugin-0.13.6-2020.1-bug234.zip)

**Comment by gardengeek99** [comment]
That fixed the issue.  However, it didn't used to require the trailing backslash in the url.  It is now required.  Feels like a regression.

**Comment by MCMicS** [comment]
Nice to hear.

Because the trailing slash i will have a look.

Do you you need official update or will you work this version until next release

**Comment by gardengeek99** [comment]
When is the next official release?  I am asking around my company to see who else is using this plugin to tell the urgency.  What you have given me works for me!  :-)

**Comment by MCMicS** [comment]
Okm
Next releaseis maybe in 2 weeks. Have 2 open issues for this. If is urgent i can upload an hotfix with this fix for 2020.1 only)

Or if your company use eap build the this way

**Comment by gardengeek99** [comment]
Gauging from the responses I am getting, 2 weeks is fine.

**Comment by gardengeek99** [comment]
A few developers use EAP, but not many.

**Comment by MCMicS** [comment]
Ok
Then it will in 0.13.7 official. I try my best to release asap

**Comment by gardengeek99** [comment]
Thank you sir!  Kudos on the quick response!

**Comment by MCMicS** [comment]
released with [0.13.7](../releases/tag/v0.13.7)
