### ISSUE TITLE
getServerUrl must not return null

### ISSUE THREAD

**Issue by pjanzen** [MCMicS/jenkins-control-plugin#239]
Hi,

Since last update of pycharm and Jenkins control plugin I cannot connect to Jenkins anymore. The error I am getting is this.

`@NotNull method org/codinjutsu/tools/jenkins/logic/JenkinsJsonParser.getServerUrl must not return null`

My configuration is this (listed in the screenshot)

Please advice.

![Screenshot 2020-07-29 06 51 03](https://user-images.githubusercontent.com/1207016/88758433-bd3e4480-d168-11ea-9743-1b5238a30d62.png)

**Comment by MCMicS** [comment]
Do you use latest version 0.13.7?
Released yetserday

**Comment by pjanzen** [comment]
Hi,

Yes, I updated this morning.

I have version 0.13.7-2020.1 installed.

**Comment by MCMicS** [comment]
Hmm strange. This should happen because the serverurl should be set in jenkins.

Which jenkins version do you use?

Is this available public to test against?

Could you send the json result of:
```<jenkins>/api/json```

**Comment by pjanzen** [comment]
Hi,

So I checked the Jenkins configuration and found a typo. It is working again. 

Thank you for your support.

Paul.

**Comment by MCMicS** [comment]
Nice to hear.
The error occurs if jenkins conf is wrong within idea or in jenkins itself.

Would great to react better to this then and i can test it
