### ISSUE TITLE
PT_BRANCH_TAG is unsupported

### ISSUE THREAD

**Issue by xicky** [MCMicS/jenkins-control-plugin#249]
![image](https://user-images.githubusercontent.com/5567116/95826557-0c0d7a80-0d65-11eb-840f-fa7c841edcbb.png)

Could you add support for this? possibly similar to #225 

The Jenkins plugin is https://plugins.jenkins.io/list-git-branches-parameter/.

**Comment by MCMicS** [comment]
I cannot retrieve any Branch Values from API.
Ic implement same logic as in #225. Show Textfield if no choices are available

![grafik](https://user-images.githubusercontent.com/4604206/95893888-9b785500-0d88-11eb-81ef-024f1fe752c5.png)

**Comment by MCMicS** [comment]
create Issue: https://issues.jenkins-ci.org/browse/JENKINS-63929

**Comment by MCMicS** [comment]
EAP version: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/versions/eap/99442

Please let know if it work for your needs

**Comment by xicky** [comment]
Although not ideal, I could just copy/paste the branch name to that input box, and the build works fine.
Thank you!

**Comment by MCMicS** [comment]
@xicky Thanks for feedback
I currently working on run configurations (#203) so that that you can predefine paramter. So you can create a configuration with your Branch name once

But this will be done in an later release

**Comment by MCMicS** [comment]
released with released with [0.13.9](../releases/tag/v0.13.9)
