### ISSUE TITLE
Are you ready to support VS Code  Jenkins Pipeline Linter Connector Similar functions

### ISSUE THREAD

**Issue by DreamPWJ** [MCMicS/jenkins-control-plugin#252]
When the pipeline is iteratively developed or becomes complex, a detector is needed to help us find errors in advance

**Comment by MCMicS** [comment]
what do you mean?
A validation of the Jenkinsfile (like 147)?

Or do you mean to use 'Command-line Pipeline Linter' from plugin (see https://www.jenkins.io/doc/book/pipeline/development/#linter)?

**Comment by DreamPWJ** [comment]
Either way, they do not support debugging in the Jenkins Shared Library way
Cannot compile Groovy files: no Groovy library is defined for module 'jenkins-shared-library'

**Comment by MCMicS** [comment]
Can you please make a short of your Intention?
Would you liketo debug your jenkinsfile locally or only compile with groovy to detect errors?

**Comment by DreamPWJ** [comment]
Local modal Shared library JenkinsFile

**Comment by DreamPWJ** [comment]
This tool can not see the running log in real time, only the running log

**Comment by MCMicS** [comment]
Your link looks like the integration of : https://www.jenkins.io/doc/book/pipeline/development/#linter

> This tool can not see the running log in real time, only the running log
Which tool? The Jenkins Idea Plugin or VS Code

**Comment by DreamPWJ** [comment]
jenkins-control-plugin

**Comment by MCMicS** [comment]
Realtime logs are Feature Request #253

Is this what you mean?

**Comment by DreamPWJ** [comment]
YES

**Comment by MCMicS** [comment]
@DreamPWJ Realtime log is implemented. What is the other indention of this issue?
Could you describe it more or close this?

**Comment by DreamPWJ** [comment]
@MCMicS It's perfect. Now it seems like there's still a little bit of downtime because you often have to cancel a running project for various reasons

**Comment by MCMicS** [comment]
Downtime and cancel project?

The plugin not cancel any build automatically.
Do you cancel the builds on jenkins?

**Comment by DreamPWJ** [comment]
I want the plugin to provide a button to cancel the task being built

**Comment by MCMicS** [comment]
Could you please create an new issue for that or change the the title of this issue.
Its hard to understand if title days vscode and you want a cancel button

**Comment by DreamPWJ** [comment]
#259

**Comment by MCMicS** [comment]
thanks for it. Could this issue closed because the other exists?
