### ISSUE TITLE
[Feature Request] Log in progress

### ISSUE THREAD

**Issue by MetalheadSanya** [MCMicS/jenkins-control-plugin#253]
Hi, thnx for great plugin.

I have feature request. Can you add display log of current build in realtime for tasks that in running status? I have a lot of work with debug build script on Jenkins and this feature will be very useful.

**Comment by MCMicS** [comment]
I will have a look at the API for this

**Comment by MetalheadSanya** [comment]
Accessing Progressive Console Output
You can retrieve in-progress console output by making repeated GET requests with a parameter. You'll basically send GET request to https://<host>/<job_path>/<build_number>/logText/progressiveText?start=0 (or https://<host>/<job_path>/<build_number>/logText/progressiveHtml?start=0 if you want HTML that can be put into <pre> tag.) The start parameter controls the byte offset of where you start.

The response will contain a chunk of the console output, as well as the X-Text-Size header that represents the bytes offset (of the raw log file). This is the number you want to use as the start parameter for the next call.

If the response also contains the X-More-Data: true header, the server is indicating that the build is in progress, and you need to repeat the request after some delay. The Jenkins UI waits 5 seconds before making the next call. When this header is not present, you know that you've retrieved all the data and the build is complete.

**Comment by MCMicS** [comment]
Thanks for the hint

**Comment by DreamPWJ** [comment]
This is very much needed

**Comment by MCMicS** [comment]
we use this lib: https://github.com/jenkinsci/java-client-api
I have a look if it offers a realtime log
If not either I change to GET call or try to implement it in the lib

**Comment by MCMicS** [comment]
I will change to stream log and build an eap version the days.

see https://github.com/jenkinsci/java-client-api/blob/ddf6a850beacf79480280c0c3c067bf73d84bca5/jenkins-client/src/main/java/com/offbytwo/jenkins/model/BuildWithDetails.java#L395

**Comment by MCMicS** [comment]
It takes still some time. Currently working on it. Have to change the Console View too

Sorry for circumstances

**Comment by MCMicS** [comment]
I've created an EAP version for 2020.3
If you need other version for eap please let me know
EAP: https://plugins.jetbrains.com/plugin/6110-jenkins-control-plugin/versions/eap/102637
Or you can add plugin repo: https://plugins.jetbrains.com/plugins/eap/list

The log could be stream with "Show last log" for running builds. A new Tool window is open with the content
It would be great if you can leave feedback for the feature

**Comment by MetalheadSanya** [comment]
Thnx very much. It works.

Maybe in feature automatically open this window when build starts, but it's feature improvement. 
Now log work correct and fast.

**Comment by MCMicS** [comment]
Thanks for feedback. Automatically open on build i'm working on. I can be delayed because it is first in queue and after time it is running

But with this request it should be included

**Comment by MCMicS** [comment]
a new EAP is available.
The Log is shown if new Build is triggered and after automatically reload a newer one is running. If the new triggered build is queued or there multiple builds it nor works for all cases. This could be an additional improvement (in my opinion) 

EAP: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=103042

Thanks for feedback

**Comment by MCMicS** [comment]
Released with 0.13.10
