### ISSUE TITLE
gitParameter  The existence of parameters is not supported

### ISSUE THREAD

**Issue by DreamPWJ** [MCMicS/jenkins-control-plugin#258]
![image](https://user-images.githubusercontent.com/16730031/101107943-6bbe2e80-360e-11eb-878c-62573ce526b5.png)
![image](https://user-images.githubusercontent.com/16730031/101107957-71b40f80-360e-11eb-897c-d1406039eb3e.png)

**Comment by MCMicS** [comment]
Yes because the git plugin in jenkins not deliver the values via API

See #225

**Comment by MCMicS** [comment]
solved with #225
