### ISSUE TITLE
Cancellation of running projects is not supported

### ISSUE THREAD

**Issue by DreamPWJ** [MCMicS/jenkins-control-plugin#259]
![image](https://user-images.githubusercontent.com/16730031/101108043-a1631780-360e-11eb-9b12-70aa8cebc961.png)

**Comment by MCMicS** [comment]
Build can be canceld via the Stop Button. Works for Job or Selected Build.

![259](https://github.com/MCMicS/jenkins-control-plugin/assets/4604206/4d4ba35d-e736-4976-90f5-29faa3f5c109)
