### ISSUE TITLE
Certificate for ... doesn't match any of the subject alternative names

### ISSUE THREAD

**Issue by fkrivsky** [MCMicS/jenkins-control-plugin#260]
We use Jenkins with self-signed SSL certificate and we're getting this error when trying to retrieve logs:
`Could not find Job data for:<job name> [job_url]. Cause: Certificate for   doesn't match any of the subject alternative names: []`

Otherwise, jobs are loaded and Build on Jenkins task is executed properly, even Refresh last completed builds works.

Versions:
- Jenkins 2.263.1
- IDEA 2020.03

**Comment by MCMicS** [comment]
Ok
Will take look at this.
Normally w use idea certificate manager. But logs are retrieved via a library and maybe this not use the certificates manager of ide.


Is the jenkins public avaliable?

**Comment by fkrivsky** [comment]
Unfortunately it's not public.

**Comment by fkrivsky** [comment]
Anyway, if that helps in any way, it is set up as follows using Docker: 
`docker run -d -v /var/lib/docker/jenkins_home:/var/jenkins_home -p 443:8443 -p 50000:50000 --name="jenkins-ssl" --restart=unless-stopped jenkins/jenkins:lts-centos --httpPort=-1 --httpsPort=8443 --httpsKeyStore=/var/jenkins_home/jenkins_keystore.jks --httpsKeyStorePassword=keypass`

jenkins_keystore.jks created with:
`keytool -genkey -keyalg RSA -alias selfsigned -keystore jenkins_keystore.jks -storepass TESTPASS -keysize 2048`

**Comment by MCMicS** [comment]
No problem. I try it with my self signed
To clarify: all actions except logs works without problems?

**Comment by fkrivsky** [comment]
Yes, I only see the error when getting logs.

**Comment by MCMicS** [comment]
Ok. I check this the days

**Comment by MCMicS** [comment]
@fkrivsky I'he tested this and with my self signed (localhost) it works
First time Intellij ask to trust the cert and then all works.

Contains your Certificate the domainname. This messages normally say that the domainname is not found
`Certificate for doesn't match any of the subject alternative names: []`

could you please test with other certificate (with given dns alternate names)
`keytool -genkey -keyalg RSA -alias selfsigned -keystore jenkins_keystore2.jks -storepass keypass -keysize 2048 -ext SAN=dns:mydomain.dev,dns:mydomain.test,dns:localhost`

is a remote session possible?

**Comment by fkrivsky** [comment]
@MCMicS - you're right - the issue is not reproducible when we use the dns params. Thanks for this workaround!

**Comment by MCMicS** [comment]
Nice to hear that this solves this
