### ISSUE TITLE
URL is malformed

### ISSUE THREAD

**Issue by wwarby** [MCMicS/jenkins-control-plugin#263]
I'm getting a `URL is malformed` error when I try to configure this plugin for Rider. The URL I've entered is `https://jenkins.tools.mycompany.com/` which is is the correct URL for Jenkins on my company's servers and takes me to the Jenkins UI in a browser. I read an old issue similar to this one in your history asking for some detail from the API - here is the result of my call to that URL:
```
<hudson _class="hudson.model.Hudson">
<nodeDescription>the master Jenkins node</nodeDescription>
<nodeName/>
<primaryView _class="hudson.model.AllView">
<name>all</name>
<url>https://jenkins.tools.mycompany.com/</url>
</primaryView>
<view _class="hudson.model.AllView">
<name>all</name>
<url>https://jenkins.tools.mycompany.com/</url>
</view>
</hudson>
```

**Comment by MCMicS** [comment]
I will lookat this the days

**Comment by wwarby** [comment]
Cheers - anything I can do to help diagnose the problem just let me know. I’m using the current version of Rider and a pretty recent version of Jenkins as it was only set up in December.

**Comment by MCMicS** [comment]
Could you please try following call: 
`http://127.0.0.1:8080/api/json?tree=url,nodeDescription`

Curl```curl
curl -v --user name:token http://127.0.0.1:8080/api/json?tree=url,nodeDescription
```

Then check the give url please

**Comment by wwarby** [comment]
The output of that URL is
```
{
_class: "hudson.model.Hudson",
nodeDescription: "the master Jenkins node",
url: "https://jenkins.tools.mycompany.com/"
}
```
Our Jenkins server is public facing - it's password protected obviously but I could ask my infrastructure team about providing temporary access if necessary. The way I normally authenticate to Jenkins is with my Google account - I wonder if authentication is the source of the problem? I had tried typing my Google credentials in the username/password boxes for the plugin which didn't help. I was initially dubious that it would have anything to do with auth because the message itself it literally telling me the URL is malformed (which it is not) but is it possible that an auth fail would lead to this message, perhaps because the plugin doesn't support federated OAuth providers for auth?

**Comment by wwarby** [comment]
I've just spoken to my infrastructure team about this and I hadn't realised that our implementation of Jenkins is hidden behind an Identityware proxy to enable authentication via Google. It works seamlessly in a web browser, but now understanding how it works I'm not surprised that a tool is unable to make a direct request to the API, and I don't think your tool can reasonably be expected to support some random third party authentication proxy, so I'll close this ticket. If you can see an easy way around the problem please do let me know, otherwise apologies for wasting your time ;)

**Comment by MCMicS** [comment]
Ok
  Behind proxy or use authentifications we  have  some issues ( like #241)
Maybe we will add some auth providers in next time

**Comment by MCMicS** [comment]
>  it's password protected obviously but I could ask my infrastructure team about providing temporary access if necessary. 
> implementation of Jenkins is hidden behind an Identityware proxy to enable authentication via Google
It is possible togrant access to me? Then it could be easier to find a solution
