### ISSUE TITLE
Please rename password label to "Password/API Token"

### ISSUE THREAD

**Issue by paulvi** [MCMicS/jenkins-control-plugin#275]
Please rename password label to "Password/API Token" in the plugin preferences

![](https://github.com/MCMicS/jenkins-control-plugin/raw/master/doc/images/Configuration-Success.png?raw=true)

So that new users don't try to put API Key into Crump Data field, or enter password when they actually have API KEY

---

Maybe even add comment that Crump Data is only for older Jenkins <2.176

See https://www.jenkins.io/doc/book/using/remote-access-api/#RemoteaccessAPI-CSRFProtection

> CSRF Protection
> Note: API tokens are preferred instead of crumbs for CSRF protection.

**Comment by MCMicS** [comment]
Thanks for create issue. This is useful and i want to add this several times. I try to do this in next release

See also #193

**Comment by paulvi** [comment]
This is UX improvement suggestion, and not related on any real technical issues like above

**Comment by MCMicS** [comment]
Yes its only UX but helps other new users

**Comment by MCMicS** [comment]
released with [0.13.12](../releases/tag/v0.13.12)
