### ISSUE TITLE
Support for IntelliJ 2021.1

### ISSUE THREAD

**Issue by obp3ter** [MCMicS/jenkins-control-plugin#277]
Are you planning on supporting the latest release? Or do I have to downgrade?

**Comment by MCMicS** [comment]
The 2020.3 version is working with 2021.1

**Comment by MCMicS** [comment]
@obp3ter Do you have problems with installing it in 2021.1

**Comment by obp3ter** [comment]
I managed to install it, but it had error because our server wasn't configured in a way that I could use it. We updated to SSO/active directory recently, which won't let me sign in correctly. I guess I'm out of luck.

**Comment by obp3ter** [comment]
![image](https://user-images.githubusercontent.com/15703843/116116256-9dba5500-a6c3-11eb-8862-27127d806351.png)
This was the exact message. I do have the necessary permissions, but it says I don't, never mind, keep on the good work, maybe there is a solution but I have no idea what. (Maybe an in-browser sign-in in combination with a Jenkins plugin?) Anyway nice work, I'll check back once in a while to see if something changed.

**Comment by MCMicS** [comment]
Hi
SSO is currently not working well in plugin. We have a feature request (#50 and #214)

Could you try to create a API token for your user and then uses this as password

**Comment by obp3ter** [comment]
I did, the above picture is the result. With my password, it's the same message but no "image" in the debug info. I think it's because it doesn't have its own DB configured anymore.

**Comment by MCMicS** [comment]
which JEnkins plugin to you use for authentification. And which AD in background

It is possible to grant access to me or it is a private jenkins

**Comment by obp3ter** [comment]
Hello, we are now using Keycloack, and sorry, but I can't give you access, it's a company server and you would need a VPN connection which is not possible.

**Comment by MCMicS** [comment]
Ok
I can try to reproduce it with own keycloak.
But I have to setup this

**Comment by elmanav** [comment]
Hi all. Are there any successes with SSO (Keycloak)?

**Comment by MCMicS** [comment]
Not yet.
i currently have a big rework the plugin for new version.

But I can look next week what is the reason why not working correctly.

**Comment by elmanav** [comment]
It would be great. I am also very annoyed by the use of single sign-on :(. But to do nothing is the policy of the company. The plugin is very valuable. Thank you.

**Comment by MCMicS** [comment]
Ok
i try to do this week a quick look
I implemented sso in other projects as well

**Comment by MCMicS** [comment]
@elamanav did you try to use api token as login?
normally it should bypass the login

point you URL to the jenkins directly or to an sso proxy in front of the server

**Comment by elmanav** [comment]
Yes, I used a API token to login and direct URL to jenkins.

**Comment by MCMicS** [comment]
And is the error the same as above or could you please attach the error.

Or even better attach this to the new issue #467
