### ISSUE TITLE
DateParameterDefinition is unsupported

### ISSUE THREAD

**Issue by xwhPanda** [MCMicS/jenkins-control-plugin#280]
DateParameterDefinition is unsupported

**Comment by MCMicS** [comment]
Which jenkins plugin offers the date parameter?

Is this one: https://plugins.jenkins.io/date-parameter

**Comment by xwhPanda** [comment]
@MCMicS Yes!

**Comment by MCMicS** [comment]
Ok
i will look at th api of the plugin and try to add them this weekend

**Comment by xwhPanda** [comment]
@MCMicS Thank you !

**Comment by MCMicS** [comment]
I've looked at the API of the plugin.
The format is not exposed via API 

So I can only offer a textfield or a single hardcoded date format

How do you use the parameter in your builds? 
If I configure a job an enter a wrong date the build is still successed but I expected an error

**Comment by MCMicS** [comment]
I think a textfield would help because it is internally also a string parameter as I see

https://github.com/jenkinsci/date-parameter-plugin/blob/3dd9c8529d72cb4ef3c4688b9821dcf86a3ce7ed/src/main/java/me/leejay/jenkins/dateparameter/DateParameterValue.java#L21

**Comment by MCMicS** [comment]
@xwhPanda I've tested it again with freestyle job instead Pipeline
Pipeline doesn't stop with wrong format but freestyle job does ends with:
> ERROR: Can't parse date format '20210512' with 'dd.MM.yyyy'

**Comment by xwhPanda** [comment]
> @xwhPanda I've tested it again with freestyle job instead Pipeline
> Pipeline doesn't stop with wrong format but freestyle job does ends with:
> 
> > ERROR: Can't parse date format '20210512' with 'dd.MM.yyyy'

![image](https://user-images.githubusercontent.com/5886598/118749737-b4059c00-b890-11eb-92ee-d834e3eed407.png)
![image](https://user-images.githubusercontent.com/5886598/118749808-d3042e00-b890-11eb-9b87-5ce6f6658604.png)

I want to dynamically generate time parameters, but an error is reported

**Comment by MCMicS** [comment]
Yes. I can it render as simple textfield and you have to ebter the value in correct format because the plugin api of dateparameter not offer the given dateformat

**Comment by MCMicS** [comment]
@xwhPanda Sorry for the delay
Could you try following plugin if it works for your needs?

[jenkins-control-plugin-0.13.12-2020.3-280.zip](https://github.com/MCMicS/jenkins-control-plugin/files/6578306/jenkins-control-plugin-0.13.12-2020.3-280.zip)

**Comment by MCMicS** [comment]
released with [0.13.12](../releases/tag/v0.13.12)

**Comment by xwhPanda** [comment]
> released with [0.13.12](../releases/tag/v0.13.12)

Thanks，this worked for me
