### ISSUE TITLE
Feature Request: Configure Action for Double Click

### ISSUE THREAD

**Issue by MCMicS** [MCMicS/jenkins-control-plugin#298]
Currentlyy a double clikc on a job triggers a new build (see #190)

It would be great to configure the action. So it will be possible to load builds instead run a new build

Ideas for possible actions:
- Trigger Build (default)
- Load Job
- Show last log
- ...

**Comment by MCMicS** [comment]
@Majed6 Could you try following EAP: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/127589

**Comment by Majed6** [comment]
Absolutely. Could you please lower the required version. I'm on 2021.1.4 ?

**Comment by Majed6** [comment]
Works like a charm. Thanks a heap for taking on my feedback. Would love to buy you a coffee, is there a place where you accept donos?

**Comment by MCMicS** [comment]
Thanks
We all are developers and help together :)

**Comment by MCMicS** [comment]
released with [0.13.12](../releases/tag/v0.13.12)
