### ISSUE TITLE
ExtensibleChoiceParameterDefinition support request

### ISSUE THREAD

**Issue by Denis-Alexeev** [MCMicS/jenkins-control-plugin#301]
Could you please support ExtensibleChoiceParameterDefinition?
<img width="373" alt="image" src="https://user-images.githubusercontent.com/52697534/125578779-461eef3e-6d28-4986-90c2-e55c8e34c234.png">

**Comment by MCMicS** [comment]
Und i check the api if all needed values are delivered

**Comment by MCMicS** [comment]
Do you use this plugin: https://plugins.jenkins.io/extensible-choice-parameter/

if yes I cheked the API a time ago and the API was not delivered all needed values. This Year I looked again and for textarea based it seems to work
Tests also "System Grrovy Choice Parameter"

WIll add this the days and give you an eap version for this

see also #159

**Comment by MCMicS** [comment]
There is another API Bug
From View I cannot receive the Choices. So I had to workaround with a extra call to get the needed values or I offer an textfield if no choices are available
[jenkins-control-plugin-0.13.12-2021.2-eap5.zip](https://github.com/MCMicS/jenkins-control-plugin/files/6820942/jenkins-control-plugin-0.13.12-2021.2-eap5.zip)


Issue in Jenkins: https://issues.jenkins.io/browse/JENKINS-66145

**Comment by Denis-Alexeev** [comment]
Unfortunately, it is not compatible with my pycharm version. Albeit I have the newest professional edition installed.
<img width="408" alt="image" src="https://user-images.githubusercontent.com/52697534/125744834-f4ab0228-39d8-499e-91ea-39499d60b955.png">

**Comment by MCMicS** [comment]
Yes it a eap for 2021.2
I can create an version for you later the day

But I'm still work on a solution to get the choices ist correctly

**Comment by MCMicS** [comment]
HEre is an version for previous version

[jenkins-control-plugin-0.13.12-2021.2-eap5-pycharm.zip](https://github.com/MCMicS/jenkins-control-plugin/files/6824337/jenkins-control-plugin-0.13.12-2021.2-eap5-pycharm.zip)

**Comment by MCMicS** [comment]
if you use following snapshot (build by myself) it will work but I don't know if and when this will be merged

rename from '.zip' to '.hpi' and install via jenkins

[extensible-choice-parameter-1.7.1-SNAPSHOT_MCMicS.zip](https://github.com/MCMicS/jenkins-control-plugin/files/6826101/extensible-choice-parameter.zip)

**Comment by Denis-Alexeev** [comment]
> HEre is an version for previous version. Still without Choices. It renders as a text input field currently
> 
> [jenkins-control-plugin-0.13.12-2021.2-eap5-pycharm.zip](https://github.com/MCMicS/jenkins-control-plugin/files/6824337/jenkins-control-plugin-0.13.12-2021.2-eap5-pycharm.zip)

Yes. It works and renders just as a text field. It is enough for me for now, because that field suggests choice of version, and by default the newest one.

> if you use following snapshot (build by myself) it will work but I don't know if and when this will be merged
> 
> rename from '.zip' to '.hpi' and install via jenkins
> 
> [extensible-choice-parameter-1.7.1-SNAPSHOT_MCMicS.zip](https://github.com/MCMicS/jenkins-control-plugin/files/6826101/extensible-choice-parameter.zip)

Unfortunately, I can't. That is not my personal Jenkins instance. I work for a company which uses Jenkins. And I'm not an administrator))

Thank you for your help! You are awesome =)

**Comment by MCMicS** [comment]
@Denis-Alexeev Thanks for feedback.
I will released it for all products with real build in next weeks.

**Comment by Denis-Alexeev** [comment]
When I open pycharm I get the error. But after closing the error window plugin works without problems. Should I open new issue for that?
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/52697534/125898732-5149c278-8705-4c9e-9af8-f0fd952e4e0c.png">

**Comment by MCMicS** [comment]
Strange that there is an nullpointer 😄 
Maybe an timing problem because it xould only happen if no JEnkins settings ar found (which is unlikely) and the current view is reset to empty during method call 

But please report if this occurs every start. Is it occuring only with my last build or also with previous versions?

**Comment by Denis-Alexeev** [comment]
- It occurs every time I start pycharm
- It occurs only with last build provided here
- I use predefined views. There are a lot of views and they contain a lot of jobs.

Is there any option 'not to download log' when I start any job via pycharm? Because it starts to daownload log. And I can't prevent or kill that downloading task. I'm forced to restsrt IDE.

**Comment by MCMicS** [comment]
> It occurs only with last build provided here
OK Maybe something get wrong with the build. 

> Is there any option 'not to download log' when I start any job via pycharm? 
no such an option not exists yet
please open an feature request for it. or the possibility to cancel download logs
is the log a long running job or why you have to restart IDE

**Comment by MCMicS** [comment]
@Denis-Alexeev I have add an option to prevent load log on trigger build
![grafik](https://user-images.githubusercontent.com/4604206/125998230-479d272f-56d5-4392-b853-81cf7e07c1ff.png)

**Comment by MCMicS** [comment]
released with [0.13.12](../releases/tag/v0.13.12)
