### ISSUE TITLE
Getting jobs from different views

### ISSUE THREAD

**Issue by zhyshkevich** [MCMicS/jenkins-control-plugin#302]
We have multiple views in Jenkins and when I select a specific one in plugin I get multiple different jobs from various views which looks like a mess eventually.

**Comment by MCMicS** [comment]
Could you provide a screenshot please

**Comment by zhyshkevich** [comment]
Actually a screenshot won't provide you any new information. Basically happening exactly what I've described in the issue and the steps are following:

1.  Select a specific view in plugin (or refresh everything).  We have around 20 views in total in Jenkins.
2.  Get a bunch of jobs from different views not only from the selected one. And if check it directly on Jenkins webpage - all is good. Can only  see the jobs dedicated to the selected view.

**Comment by MCMicS** [comment]
Is the jenkins public to test against?

In my tests the views works but i try to reproduce it. It could be a timing problem if switched between views or the api from jenkins is broken

Could you open your view in browser and append '/api/json' to it and send me the json (or look if job array contains only wanted jobs

**Comment by zhyshkevich** [comment]
Ok, I've located the root of the issue and it's probably connected to out Jenkins server config.
The view I'm interested in is set as a _primary_ one (because it's the most used one) and it points to the root url (aka **dumbjenkinsserver.com/**). So whenever I visit **dumbjenkinsserver.com/**, the desired view is already being opened.
But once I tried **dumbjenkinsserver.com/api/json**, I got a huge list of jobs (probably all the jobs in general) and this is exactly what I'm getting in the plugin right now.
Once I tried **dumbjenkinsserver.com/view/BaseView/api/json** I got exactly what I expected the plugin to return from the beginning: a list of jobs dedicated to the selected view.

So my assumption is that the plugin fetches the primary view and it's link, but it doesn't know (and it couldn't) that it should be redirected to the specific view link (what our server apparently does) and just makes a call to the root url and retrieves all the jobs but still thinks that it's a selected view.

**Comment by zhyshkevich** [comment]
Is there a way to point directly to a specific view only rather than to the whole Jenkins server in the plugin config?
I've tried to set it up, but got the following exception:
`**Jenkins Server Path Mismatch: expected='/view/BaseView/' - actual='/'. Look at the value of 'Jenkins URL' at dumbjenkinsserver.com/view/BaseView/configure**`
Though if I try just **dumbjenkinsserver.com/view/BaseView** in a browser, it works fine.

**Comment by MCMicS** [comment]
No I can try to load the view explicitly

I try it out the days

**Comment by zhyshkevich** [comment]
Ok, thanks for quick support on this. 
This issue can be closed I guess since the problem is not related to the plugin itself.

**Comment by MCMicS** [comment]
Ok
i will still have look if one workaround exists.
If it is a small change i can add it to next release
