### ISSUE TITLE
Jenkins Logs report Status code 401 or 403

### ISSUE THREAD

**Issue by achievejia** [MCMicS/jenkins-control-plugin#334]
![image](https://user-images.githubusercontent.com/12773008/138124947-3ef892d6-1c74-45c8-af3b-a212aa8a43fc.png)

**Comment by achievejia** [comment]
This problem occurred just after I installed it. I used the user name and password plus crumd to test the connection, and they were all successful. And you can build directly, but you can’t see the log. When you look at the log, it reports 401 or 403.
This server is a server belonging to our company’s intranet, and cannot be exported for testing.

**Comment by MCMicS** [comment]
This seems correct at first look

You you retry the curl command for the job
```
curl -v -u user:apiToken jenkinsURL/job/saas-public-pay/api/json
```

If still not work I will have a closer look next week on this
