### ISSUE TITLE
Support git parameter plugin

### ISSUE THREAD

**Issue by han1448** [MCMicS/jenkins-control-plugin#366]
Hi. 
I'm using jenkins plugin well.
Recently I add [git parameter plugin](https://plugins.jenkins.io/git-parameter/) to my jenkins.

However, string parameter works find, but git parameter does not seem to be supported.
It would be great if this feature could be supported.

<img width="379" alt="스크린샷 2022-03-31 오후 12 54 15" src="https://user-images.githubusercontent.com/4098287/160975066-d1b9a2d0-085b-44c7-9b64-8fc302c270aa.png">

**Comment by MCMicS** [comment]
I will have a look and add it if possible

**Comment by MCMicS** [comment]
I have tested it:
An it seems to broken. I fix it

**Comment by MCMicS** [comment]
Could you try following eap please: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/165315

**Comment by MCMicS** [comment]
solved in https://github.com/MCMicS/jenkins-control-plugin/commit/4711cebd3ae3c437990ff0c5d814af92af43fa51

**Comment by han1448** [comment]
@MCMicS 
Sorry for the late reply and thanks
