### ISSUE TITLE
Getting a 500 error when trying to login in to Jenkins

### ISSUE THREAD

**Issue by sjahangir1** [MCMicS/jenkins-control-plugin#386]
My organisation is running Jenkins v2.3.55 and I am getting a 500 error code whenever I try to authenticate the plugin
![Screenshot 2022-06-24 125002](https://user-images.githubusercontent.com/103427525/175528656-bebb601d-bee2-4488-b7c6-8b0da0ff4199.png)
.

**Comment by MCMicS** [comment]
@sjahangir1 Is this still present on your side with latest plugin version?

if yes please reopen this issue and attach log of jenkins server
