### ISSUE TITLE
Paramaters window too big for screen

### ISSUE THREAD

**Issue by fschwa** [MCMicS/jenkins-control-plugin#391]
Hi,

we have jobs with many parameters so when I try to run such a job, the parameters window is bigger than my screen and I cannot reach the "OK" button. If would be nice to have the contents of that window scrollable.

Cheers

**Comment by MCMicS** [comment]
thanks for that request. Till be scheduled for one of next releases

**Comment by Les-Linux** [comment]
Hello @MCMicS,
I have an issue very similar to this, in that the pop up window extends the entire width of my large monitor. I cannot resize this i.e. make it smaller. Is there a way to resize this menu?
![jenkins-plugin-capture](https://user-images.githubusercontent.com/1759713/212885417-a6f73b67-6585-4700-94e1-36e5133bc256.jpg)

Good Job on the Plugin!

Les

**Comment by MCMicS** [comment]
I check if I can makee it resizable

**Comment by Les-Linux** [comment]
thank you very much, if I can be of any assistance just let me know @MCMicS

**Comment by MCMicS** [comment]
@fschwa @Les-Linux Can you please test following EAP: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/285901

Maybe it fits the needs. The window is now resizable and the last width will be restored on next call

**Comment by Les-Linux** [comment]
Good Evening,

I just applied the plugin and I now successfully can resize the window. Thank you very much for this!

When I issue a new call however, the previous width is not remembered. See attached image.

My IntelliJ Version: Build #IU-223.8617.56, built on January 26, 2023

Again, thank you very much for such a nice tool and for all your assistance.

Les

￼

**Comment by MCMicS** [comment]
I check the restoring of size tomorrow again. Maybe I forget something
Or I use a default width with static size for initial showing

**Comment by MCMicS** [comment]
@Les-Linux I didn't see an attached imager. Could you please provide from web UI

**Comment by Les-Linux** [comment]
Hi MCMicS,

I was travelling the last couple of days and only returned to office today, apologies for my late response. Do you still require the images for reference?

Les

**Comment by MCMicS** [comment]
Hi
yes if the problem still exists. Or create a new issue that previous size is not restored.

But resizing of the dialog should work

**Comment by MCMicS** [comment]
released with [0.13.17](../releases/tag/v0.13.17)
