### ISSUE TITLE
Need Proxy

### ISSUE THREAD

**Issue by zhouyijiaren** [MCMicS/jenkins-control-plugin#406]
Our Jenkins is running after the protection of Nginx Basic Auth. So I need to add a proxy server that supports the Basic Auth, and I have set the IDEA's HTTP proxy and tested the connection. But this plus can never use the proxy(I don't see the trace in the monitor of the proxy server ). 

Request:
1. the way to use a global proxy.
2. or add function to use proxy.

**Comment by MCMicS** [comment]
Can you please test with following eap:

https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/263516

I added proxy usage of intellij proxy settings

**Comment by MCMicS** [comment]
Hi
can you please use latest version (0.13.16)
it will be use the proxy settings from IntelliJ

![grafik](https://user-images.githubusercontent.com/4604206/212835047-db0e65e6-e52f-4897-9a96-e546cfcf01c4.png)

**Comment by zhouyijiaren** [comment]
This is my solution:
  Use the `Charles` to rewrite the Basic Auth, which I found in my web Request.
I haven't tested your solution, Because I don't know how to start a `proxy server` myself without a special tool.

**Comment by MCMicS** [comment]
Have you tried the intellij proxy settings?
this should be used

but i can check the days

**Comment by mwisnicki** [comment]
I have basic job listing working on 0.13.16-2021.2 but for example trying to `Show last log` fails with a red tooltip `status code 407, reason phrase: Proxy Authentication Required`.

Looks like usage of proxy auth is not very consistent. Luckily I don't need proxy for that url and `No proxy for` was obeyed once I fixed it.

**Comment by MCMicS** [comment]
I check if I missed one proxy usage

**Comment by MCMicS** [comment]
I reproduced it and fix it
thanks for that

**Comment by MCMicS** [comment]
Can you please try following: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/293869

**Comment by MCMicS** [comment]
new build with improved redirect handling: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/296705

**Comment by MCMicS** [comment]
released with [0.13.17](../releases/tag/v0.13.17)
