### ISSUE TITLE
Unable to enter parameters

### ISSUE THREAD

**Issue by 15216422268** [MCMicS/jenkins-control-plugin#415]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/36149947/205602227-1d7be4d5-271f-47a5-9fbb-bd5fd32df863.png">
<img width="856" alt="image" src="https://user-images.githubusercontent.com/36149947/205602357-7624e675-ff4d-4f78-8bca-b76383d4ce83.png">
Unable to enter parameters
Unable to enter parameters

**Comment by MCMicS** [comment]
I have added it but I need a little change to show validation errors in UI. If there are error no build is triggerd but shows as succesful

**Comment by MCMicS** [comment]
Can you please check Following EAP: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/261695

**Comment by 15216422268** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/36149947/205787964-b35ca438-0023-4c32-9265-58fee99e23b5.png">
It is available, thank you very much for your support!

**Comment by MCMicS** [comment]
released with [0.13.16](https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/stable/277685)
