### ISSUE TITLE
URL is malformed

### ISSUE THREAD

**Issue by GitXiaoPing** [MCMicS/jenkins-control-plugin#434]
hello,Help me look at this problem.
![image](https://user-images.githubusercontent.com/45633931/212678237-3fdff87e-a16c-4c54-8612-fc94749cb4e8.png)
![image](https://user-images.githubusercontent.com/45633931/212678316-bb43b2e3-f1f8-4b07-a8c3-ee88e312e88c.png)

**Comment by GitXiaoPing** [comment]
I use IDEA 2022.3.1

**Comment by GitXiaoPing** [comment]
Jenkins version 
![image](https://user-images.githubusercontent.com/45633931/212683643-d10ad29a-8e52-41b6-8b31-2eb327e95329.png)

**Comment by GitXiaoPing** [comment]
> 
I use the java method to start , Tomcat startup is the same problem ，Let me test it with the latest version。
![image](https://user-images.githubusercontent.com/45633931/212685955-c2f6d0ec-f0d5-463f-8bf6-7161c6eeb1fa.png)

**Comment by GitXiaoPing** [comment]
> If you use a non Jetty deployment (like tomcat) there is currently a bug in our software.
> 
> I create a new release today. Or you can try the latest version from issue #426
> 
> if this version not works please let me know

Thank you very much. I can use the latest version. Java and tomcat can be accessed
![image](https://user-images.githubusercontent.com/45633931/212688776-ba1919c7-7291-4bac-9816-5b3f2c4159d7.png)

**Comment by MCMicS** [comment]
OK I will check again later

if you can check the latest version it would be nice

**Comment by GitXiaoPing** [comment]
> 
Thank you.
![image](https://user-images.githubusercontent.com/45633931/212689348-2825b894-6735-4b9a-901d-cd127514b9c9.png)

**Comment by MCMicS** [comment]
Thanks for test. Then it was also the issue with wrong encoding
i release the version today

**Comment by GitXiaoPing** [comment]
OK, I will update it immediately if the latest version is released.


wxp
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCMicS/jenkins-control-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月16日(星期一) 晚上9:45
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [MCMicS/jenkins-control-plugin] URL is malformed (Issue #434)





 
Thanks for test. Then it was also the issue with wrong encoding
 i release the version today

**Comment by MCMicS** [comment]
released with [0.13.16](https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/stable/277685)

**Comment by GitXiaoPing** [comment]
hello,The problem I have now is that my company uses the proxy method to access jenkins. Now the plug-in reports the following information






wxp
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCMicS/jenkins-control-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月17日(星期二) 凌晨3:39
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [MCMicS/jenkins-control-plugin] URL is malformed (Issue #434)





 
released with 0.13.16

**Comment by MCMicS** [comment]
Hi cant see the error
could you please upload the image or paste the message to this issue.

I use the proxy settings from Idea. Is this configured there?

**Comment by GitXiaoPing** [comment]
Jenkins Server Port Mismatch: expected='81' - actual='8080'. Look at the value of 'Jenkins URL' at http://localhost:81/jenkins/configure
&nbsp;


wxp
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月17日(星期二) 晚上9:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [MCMicS/jenkins-control-plugin] URL is malformed (Issue #434)






嗨看不到错误
能否请您上传图片或粘贴邮件到这个问题。

我使用Idea的代理设置。这个配置在那里吗？

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by MCMicS** [comment]
Oh
yes it sounds like #377
I have a dev version for it because Im working on it. I hope I can finish it the next weeks

**Comment by MCMicS** [comment]
For then itself  is currently not possible to have different hostnames (configured in jenkins and configured in IDEA)

If the usage is important I can disable the check and provide a special version

**Comment by GitXiaoPing** [comment]
Agent configuration in nginx








wxp
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCMicS/jenkins-control-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月17日(星期二) 晚上10:14
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [MCMicS/jenkins-control-plugin] URL is malformed (Issue #434)





 
For then itself  is currently not possible to have different hostnames (configured in jenkins and configured in IDEA)
 
If the usage is important I can disable the check and provide a special version

**Comment by MCMicS** [comment]
I cant see the nginx config in browser. Can you please attach it
