### ISSUE TITLE
Nginx proxy access

### ISSUE THREAD

**Issue by GitXiaoPing** [MCMicS/jenkins-control-plugin#437]
Hello in the reverse direction, I am using the nginx proxy jenkins to access, and encountered the following error:
![image](https://user-images.githubusercontent.com/45633931/213175906-bf5b65c4-4aa4-4413-bcb7-ed87828c7c60.png)
![image](https://user-images.githubusercontent.com/45633931/213175932-ca3680b6-c7dc-40e4-91b3-9338b1230eda.png)
![image](https://user-images.githubusercontent.com/45633931/213176321-aac68eaa-b5ed-48ed-b5e0-ca6bcf129086.png)

**Comment by GitXiaoPing** [comment]
Jenkins Server Port Mismatch: expected='81' - actual='8080'. Look at the value of 'Jenkins URL' at http://localhost:81/jenkins/configure

**Comment by MCMicS** [comment]
You have to setup you jenkins url within jenkins settings. If you always use the connection throught nginx you have to set this url as Jenkins root Url

Go to: 
http://localhost:81/jenkins/manage/configure

And set localhost.81/jenkins as URL

See also jenkins doc: https://www.jenkins.io/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx/


The the reverse proxy will work

**Comment by MCMicS** [comment]
What mean 'You can modify the configuration.'

should the plugin change the config or it means that you as jenkins admin has to change the url?
