### ISSUE TITLE
Show log of a selected build

### ISSUE THREAD

**Issue by jacekgajek** [MCMicS/jenkins-control-plugin#450]
Currently there is an option to show a log of last build, last successful build and last failed build. It'd be nice to view logs of a selected build after clicking "Load Builds". Currently there is only an option to go to a build/console page.

![image](https://user-images.githubusercontent.com/68021034/218724518-54ec004a-ef90-46af-bb38-8bd89122ad9f.png)

**Comment by MCMicS** [comment]
You can show last log after trigger build to show the current running log

also a setting exists to show log on trigger build

**Comment by MCMicS** [comment]
Ah 
i misunderstood I think.

You want to show the log for a specific build in IDE?

**Comment by MCMicS** [comment]
@jacekgajek Pleases give following EAP a try: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/292490

**Comment by MCMicS** [comment]
released with [0.13.17](../releases/tag/v0.13.17)
