### ISSUE TITLE
[Cosmetics] separate "Run/Stop on Jenkins" by splitter

### ISSUE THREAD

**Issue by jacekgajek** [MCMicS/jenkins-control-plugin#461]
![image](https://user-images.githubusercontent.com/68021034/221559490-5cea8d00-742a-4940-9204-7438b576c71e.png)

**Action**

I click on "Stop On Jenkins" 

**Expected**

Logs are shown

**Actual**

"Stop On Jenkins" is executed

I can see my future self clicking this accidentally.
Suggestion: Move "Stop on Jenkins" to the last position, separated by a splitter

**Comment by MCMicS** [comment]
Thanks for Feedback
Sounds great to move the action.

But the description says that it is expected to showq logs if you click on "Stop on Jenkins". I think this is just a typo isn't?

**Comment by jacekgajek** [comment]
It was a joke :)

**Comment by MCMicS** [comment]
released with [0.13.18](../releases/tag/v0.13.18)
