### ISSUE TITLE
Configurable/limit number of displayed builds

### ISSUE THREAD

**Issue by jacekgajek** [MCMicS/jenkins-control-plugin#463]
I think a number of displayed jobs should be configurable, ideally with number of days or hours. In my environment builds are executed all the time but usually I'm interested in those which were started today (or last 24 hours). Other people might have different expectation but in general I think nobody wants to see month-old builds  _by default_. Actually I'm not sure how the number of builds is chosen, seems to be random

The most simple solution is to add setting to preferences and if user wants to see more builds then they need to change configuration.

A more complex solution would be adding some kind of a "show more" button in the list. I don't know whether the tree widget you use already has it or not.

![image](https://user-images.githubusercontent.com/68021034/223395917-2b3a314e-e855-49b2-a9f9-60f056c3a135.png)

Sorry for spamming you with suggestions, but I really like the plugin :)

**Comment by MCMicS** [comment]
Thanks for that
i will look what is possible

**Comment by MCMicS** [comment]
in EAP you can test the possibility to configure the max number of builds to load.
https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/374489

**Comment by MCMicS** [comment]
released with [0.13.19](https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/stable/408555)
