### ISSUE TITLE
Add Support for SSO

### ISSUE THREAD

**Issue by MCMicS** [MCMicS/jenkins-control-plugin#467]
Follow Up from #277

- [x] Keycloak - OpenId Connect Authentication (https://plugins.jenkins.io/oic-auth/)
- [x] Github - GitHub Authentication (https://plugins.jenkins.io/github-oauth/)
- [x] Openshift

Reference to #50 and #214

Please support login for SSO like Keycloak, github or Openshift

**Comment by MCMicS** [comment]
@elmanav
I have setup a keycloak to test it and it works.
I use Keycloak and ion Jeknins the OpenID plugin:
![grafik](https://user-images.githubusercontent.com/4604206/229369776-e0e543d2-9cad-4d9c-b31a-5863e8477e93.png)

**Comment by elmanav** [comment]
All OK!!!
Jenkins itself was not configured properly. Sorry ((((
Thanks for the tool.

**Comment by elmanav** [comment]
Super!
Great job.

**Comment by MCMicS** [comment]
Works as it seems working with correct configuration.
Tested with (Intellij Ultimate and PyCharm Community):
- Keycloak
- Github
- Openshift

For any issue with SSO provider please create ne issue.
