### ISSUE TITLE
Doesn't work when Jenkins is using Github OAUTH plugin for authentication

### ISSUE THREAD

**Issue by henryguillen** [MCMicS/jenkins-control-plugin#50]
https://wiki.jenkins-ci.org/display/JENKINS/Github+OAuth+Plugin

Returns
Status Code: 401
Exception: Unexpected authentication type: org.acegisecurity.providers.UsernamePasswordAuthenticationToken@e8133c3: Username: HGuillen217; Password: [PROTECTED]; Authenticated: false; Details: org.acegisecurity.ui.WebAuthenticationDetails@0: RemoteIpAddress: 23.31.128.233; SessionId: null; Not granted any authorities Stacktrace:
(none)

**Comment by jereanon** [comment]
Hi @IgorGanapolsky / @dboissier , I know it's been about a year since this has been addressed, but any chance to revisit this issue?

thanks

**Comment by IgorGanapolsky** [comment]
I have long moved away from Jenkins.  I've enjoyed the free cloud-hosted
Travis-ci since.

Thanks,
Igor

**Comment by chenfli** [comment]
HI @dboissier , any news regarding this issue. I am using webstrom 2016.3.1 and since jenkins doesn't support both Github oauth and user password, I can't use the plugin.

It looks awesome.

**Comment by iwex** [comment]
I'm not sure, but you can use email as 'user' and jenkins api token as 'password'

**Comment by kskourtis** [comment]
I got around this by using my jenkins api token as the password (along with my normal username)

**Comment by charj** [comment]
+1 I'm also unable to use your plugin as we use GitHub OAuth. Good work so far on the plugin!

**Comment by szczad** [comment]
Hi @dboissier. The project seems promising, but unfortunately it still cannot connect to Jenkins with Github OAuth plugin. Is there any chance to have such feature in future releases?

**Comment by Habitats** [comment]
Any plans for adding support for GitHub login?

**Comment by MCMicS** [comment]
Yes but not in next releases. Want to support github and openshift

**Comment by Habitats** [comment]
Great! Is there a workaround available for those who have GH auth enabled? I would really like to use this plugin.

**Comment by MCMicS** [comment]
I've do an short test. If you create an API Token in Jenkins and use this it will work also with Github Auth.

Can you confirm this?

**Comment by MCMicS** [comment]
Works with latest release.

see #467
