### ISSUE TITLE
Specify `id` in plugin.xml matching getId() value

### ISSUE THREAD

**Issue by YannCebron** [MCMicS/jenkins-control-plugin#507]
https://github.com/MCMicS/jenkins-control-plugin/blob/1b03c07759adb51359ba3404571e0a3b5759b2b9/src/main/resources/META-INF/plugin.xml#L64

required for 2023.2

**Comment by MCMicS** [comment]
Thanks for the hint

**Comment by MCMicS** [comment]
released with [0.13.19](https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/stable/408555)
