### ISSUE TITLE
No valid crumb was included in the request

### ISSUE THREAD

**Issue by delanym** [MCMicS/jenkins-control-plugin#510]
Pictures tell a thousand words

![image](https://github.com/MCMicS/jenkins-control-plugin/assets/5310238/33484179-c14d-4b19-af60-194881591110)

Plugin version 0.13.18-2023.2
Jenkins 2.387.3 core

I tried enabling proxy, but could not disable CRSF as there's no longer an option
https://stackoverflow.com/questions/44711696/jenkins-403-no-valid-crumb-was-included-in-the-request

![image](https://github.com/MCMicS/jenkins-control-plugin/assets/5310238/32f9998c-f181-4156-8dc2-3272c1d4e6d6)

**Comment by MCMicS** [comment]
Do you have use the password?

It is recommend to use api token which can be created for your user

**Comment by delanym** [comment]
Seems the copy token button in Jenkins didn't actually populate the clipboard, so I pasted something that was not a Jenkins token.
Thanks, it works now
