### ISSUE TITLE
Does not work with form-based authentication

### ISSUE THREAD

**Issue by jirutka** [MCMicS/jenkins-control-plugin#53]
Does this plugin support form-based authentication? It does not work for me, when I enter URL, username and whatever password in the settings dialog, then _“Test Connection_ returns _[Fail] Server Internal Error: Server Unavailable”_. I’m using HTTPS with trusted certificate.

**Comment by MCMicS** [comment]
I think it is closed because we use newer http client library within Idea.
If not please reopen or file a new issue.
