### ISSUE TITLE
How can I organize or order my Git branches

### ISSUE THREAD

**Issue by esiazy** [MCMicS/jenkins-control-plugin#541]
I use Jenkins with Git parameters, but I have a large number of Git branches. 
How can I organize or order my Git branches？

thank u

**Comment by MCMicS** [comment]
Hi
what do you mean?
The order of branches in multibranch job or the the parameter?
Or do you mean the parameter list/text in build project dialog

can you share a screenshot or screen record of this.

**Comment by esiazy** [comment]
Your response has inspired me. I should modify the settings of the pipeline on Jenkins so that the plugin can display the branches in the correct order.
