### ISSUE TITLE
Adopt dependabot

### ISSUE THREAD

**Issue by gregallen** [MCMicS/jenkins-control-plugin#542]
Please enable dependabot under GitHub insights tab. The plugin is being flagged for security vulnerabilities in a corporate environment preventing its use. Thanks!

**Comment by MCMicS** [comment]
Thanks
i will do

**Comment by gregallen** [comment]
Oh yes. My mistake. Vulnerabilities were seen in 0.13.19-2023.2. 

I see the dependabot updates were more recent than that. 

Any chance of a new release still supporting 2023.2.x?

Thanks!

**Comment by MCMicS** [comment]
@gregallen Can you yo show where to find your Vulnerabilities?
i didnt see anything for dependabot in security tab
only some warning for code scanning

**Comment by MCMicS** [comment]
Feel free to reopen for found vulnerabilities
