### ISSUE TITLE
Clicking "Show tests results" is bugged

### ISSUE THREAD

**Issue by muliyul** [MCMicS/jenkins-control-plugin#571]
Having multiple jobs running, viewing their logs simultaneously and finally attempting to view the test results, results in only one of them being opened.

Say I run jobs: A, B

After both finish, I'm presented with the ability to view test results, but when I click it (after ensuring focus for the correct job) I'm presented with A's test results.

**Comment by muliyul** [comment]
Just figured out - the problem is that the button is always bound to the last executed job rather than the one focused.

**Comment by MCMicS** [comment]
Thanks I will have a look

**Comment by MCMicS** [comment]
@muliyul I tested it and you are right. I use the selected Job in Tree.

I will change it. I'm currently prepare the next release. I cannot promise to fix it in it but I try

Thanks for Report.

https://github.com/MCMicS/jenkins-control-plugin/assets/4604206/812111c4-a3c4-4267-ba91-6a2af7131864

**Comment by MCMicS** [comment]
will be fixed in next release

**Comment by MCMicS** [comment]
released with [0.13.20](https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/stable/512135)
