### ISSUE TITLE
Long IDEA startup time when CI server host is unreachable

### ISSUE THREAD

**Issue by attr** [MCMicS/jenkins-control-plugin#59]
It takes ages for IDEA to start up if the Jenkins server host is unreachable.

**Comment by cezary-butler** [comment]
This issue exists because network communication is done in ui thread, when should be done in background thread. I'm already onto that.

**Comment by cezary-butler** [comment]
This is already fixed on https://github.com/Programisci/jenkins-control-plugin
You can download binary package at http://programisci.eu/en/jenkins-control-plugin/

After some testing I'll submit pull request to David repository.

**Comment by dboissier** [comment]
Hi,

The plugin has been fixed by @cezary-butler. It is deployed on jetbrains repository and may fix the issue you encounter

**Comment by MCMicS** [comment]
If error still occurs with 0.11.0 please feel free to reopen.
