### ISSUE TITLE
Icon on white theme looks no good

### ISSUE THREAD

**Issue by anton-panfilov** [MCMicS/jenkins-control-plugin#598]
![image](https://github.com/MCMicS/jenkins-control-plugin/assets/1083546/fe1b5e10-f24f-44e3-81bf-03907bb72121)

**Comment by MCMicS** [comment]
Which version do you use?
Do you use new UI in IDE?

**Comment by MCMicS** [comment]
So now all is correct and this can be closed?

**Comment by anton-panfilov** [comment]
yes, correct
