### ISSUE TITLE
ComboBox Lacks Search Functionality for Large Number of Choices

### ISSUE THREAD

**Issue by LakeLab** [MCMicS/jenkins-control-plugin#656]
There is an issue where it is difficult to navigate through the options in the ComboBox when there are many choices, as it does not support search functionality.

I plan to address this issue by submitting a PR that introduces a solution to enhance usability in such scenarios. Stay tuned, please!

**Comment by LakeLab** [comment]
I have submitted [a PR](https://github.com/MCMicS/jenkins-control-plugin/pull/657) to address this issue. Please review it at your earliest convenience. Thank you!  @MCMicS

**Comment by MCMicS** [comment]
Thanks for creating and implementing

**Comment by LakeLab** [comment]
Thank you for your prompt response!
I apologize for overlooking the test codes earlier. I’ll update the PR to address the issues in my changes using your test codes.

**Comment by LakeLab** [comment]
I just uploaded the [PR](https://github.com/MCMicS/jenkins-control-plugin/pull/658) to address the issue of my code changes for this issue with the test code! Thank you!
