### ISSUE TITLE
IntelliJ 12.1.6 RSS feed not working

### ISSUE THREAD

**Issue by Nieschinhio** [MCMicS/jenkins-control-plugin#76]
Hi,

thanks for the very helpful plugin. Unfortunately the rss feed seems not to get picked up. I managed it only once to get a rss message inside the event log by jenkins. But except of this I never see any message from jenkins inside the log. It does not work either automatically (5 minutes) nor manually by hitting the button. The job view works as intended.

Any ideas?

**Comment by dboissier** [comment]
Hi,

please test the latest version of the plugin and tell me if it works.

Sorry for being late in processing your request

**Comment by MCMicS** [comment]
If error still occurs with 0.11.0 please feel free to reopen.
