### ISSUE TITLE
Support text parameters in builds

### ISSUE THREAD

**Issue by RobFreundlich** [MCMicS/jenkins-control-plugin#80]
The ability to support parameters in builds is great.  Can you please enhance it by supporting TextParameterDefinition parameters as in the following?

![image](https://cloud.githubusercontent.com/assets/7975013/3370937/71959710-fb98-11e3-8cf9-2cad7a1623b5.png)

Thanks!

**Comment by MCMicS** [comment]
![grafik](https://user-images.githubusercontent.com/4604206/73595124-10667000-4515-11ea-9ade-1091dcdf4518.png)

Sample Pipeline config:
```
   parameters {
       string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
       text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
       booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
       choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
       password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
   }
```
