### ISSUE TITLE
after restarting pycharm it only throws Illegal State Exceptions for Jenkins plugin

### ISSUE THREAD

**Issue by golodhrim** [MCMicS/jenkins-control-plugin#85]
All I get from Pycharm atm from jenkins plugin is:

IllegalStateException: Access from read action is not allowed, because it might lead to a deadlock.: Access from read action is not allowed, because it might lead to a deadlock.

how can it be fixed?

Greetings

**Comment by dboissier** [comment]
Hi,

The plugin has been fixed by @cezary-butler. It is deployed on jetbrains repository and may fix the issue you encounter

**Comment by MCMicS** [comment]
If error still occurs with 0.11.0 please feel free to reopen.
